openapi: 3.1.0
info:
  title: ECHOHUB API
  description: >-
    API Endpoints for the ECHOHUB Project.


    # Authentication

    Authentication is a process by which a system verifies the identity of a
    user accessing this API.       


    <!-- ReDoc-Inject: <security-definitions> -->
  version: v1
  termsOfService: https://example.com
  contact:
    name: ECHO Health Inc.
    url: https://echohealthinc.com
    email: Echo_Hub@echohealthinc.com
externalDocs:
  description: |
    description external docs text
  url: 'https://example.server.io'
servers:
  - url: /v1
security:
  - x-ApiKey: []
  - x-ClientKey: []
paths:
  /api/Authentication/v1/Authentcation:
    $ref: paths/Authentication/api@RequestAuthentication@V1.yaml
  /api/eCheck/v1/MPXECheckPayeeContact: 
    $ref: paths/Echecks/api@eCheck@v1@MPXECheckPayeeContact.yaml
  /api/DirectPay/Deluxe/v1/DeluxeEcheck:
    $ref: paths/Echecks/api@DirectPay@Deluxe@v1@DeluxeEcheck.yaml
  # /api/DirectPay/Deluxe/v1/DeluxeEcheckCancel:
  #   $ref: paths/api@DirectPay@Deluxe@v1@DeluxeEcheckCancel.yaml
  # /api/MedPay/V1/UpdateBlockedVCard:
  #   $ref: paths/api@MedPay@V1@UpdateBlockedVCard.yaml  
  /api/VCP/V1/CardActivity:
    $ref: paths/VCP/api@VCP@V1@CardActivity.yaml
  /api/VCP/V1/CardCancel:
    $ref: paths/VCP/api@VCP@V1@CardCancel.yaml
  /api/DirectPay/DirectToDebit/v1/DirectToDebitPayment:
    $ref: paths/DirectToDebit/api@DirectPay@DirectToDebit@v1@DirectToDebitPayment.yaml
  /api/DirectPay/DirectToDebit/v1/DirectToDebitCancel:
    $ref: paths/DirectToDebit/api@DirectPay@DirectToDebit@v1@DirectToDebitCancel.yaml
  /api/DirectPay/DirectToDebit/v1/DirectToDebitStatus:
    $ref: paths/DirectToDebit/api@DirectPay@DirectToDebit@v1@DirectToDebitStatus.yaml
  /api/DirectPay/Venmo/v1/VenmoPayment:
    $ref: paths/Venmo/api@DirectPay@Venmo@v1@VenmoPayment.yaml
  /api/DirectPay/Venmo/v1/VenmoCancel:
    $ref: paths/Venmo/api@DirectPay@Venmo@v1@VenmoCancel.yaml
  /api/DirectPay/Venmo/v1/VenmoStatus:
    $ref: paths/Venmo/api@DirectPay@Venmo@v1@VenmoStatus.yaml
  /api/DirectPay/Zelle/v1/ZellePayment:
    $ref: paths/Zelle/api@DirectPay@Zelle@v1@ZellePayment.yaml
  /api/DirectPay/Zelle/v1/ZelleCancel:
    $ref: paths/Zelle/api@DirectPay@Zelle@v1@ZelleCancel.yaml
  /api/DirectPay/Zelle/v1/ZelleStatus:
    $ref: paths/Zelle/api@DirectPay@Zelle@v1@ZelleStatus.yaml
  /api/DirectPay/v1/PaymentCancel [For Deluxe]:
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalDeluxeCancel.yaml
  /api/DirectPay/v1/PaymentCancel [For Direct To Debit] :
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalDirectToDebitCancel.yaml
  /api/DirectPay/v1/PaymentCancel [For Venmo] :
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalVenmoCancel.yaml
  /api/DirectPay/v1/PaymentCancel [For Zelle] :
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalZelleCancel.yaml
  /api/DirectPay/v1/PaymentCancel [For VCP] :
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalVCPCancel.yaml
  /api/DirectPay/v1/PaymentStatus [For Direct To Debit] :
    $ref: paths/UniversalStatus/api@DirectPay@v1@UniversalDirectToDebitStatus.yaml
  /api/DirectPay/v1/PaymentStatus [For Venmo] :
    $ref: paths/UniversalStatus/api@DirectPay@v1@UniversalVenmoStatus.yaml
  /api/DirectPay/v1/PaymentStatus [For Zelle] :
    $ref: paths/UniversalStatus/api@DirectPay@v1@UniversalZelleStatus.yaml
  /api/DirectPay/v1/PaymentStatus [For VCP] :
    $ref: paths/UniversalStatus/api@DirectPay@v1@UniversalVCPStatus.yaml
  /api/DirectPay/v1/PaymentVoid:
    $ref: paths/UniversalVoid/api@DirectPay@v1@UniversalDeluxeVoid.yaml   
components:
  securitySchemes:
    x-ApiKey:
      type: apiKey
      name: x-ApiKey
      description: The API key.
      in: header
    x-ClientKey:
      type: apiKey
      description: The client key.
      name: x-ClientKey
      in: header
    x-Authorization:
      scheme: x-Authorization
      type: http
      description: The Authorization Token.
      
tags:
  - name: Authorization 
    description: |
      This End point Helps to generate the Authentication token for Accessing the End points   
  - name: eCheck
    description: >
      An eCheck, or electronic check, is a digital version of a paper check that
      is used to make a payment online.    

      With an eCheck, money is electronically withdrawn from the Payor’s
      checking account. Money is transferred over the ACH (Automated Clearing House) network and
      deposited into the Payee’s checking account.

  - name: Direct To Debit
    description: |
      Direct To Debit is the simplest and most convenient way to make payments. It is a type of pre-authorized payment that allows a bank to pay a certain amount directly to the provider with a debit card. With Direct To Debit payments, the money is directly transferred to the cardholder.  
      Direct To Debit has three endpoints:  
       * Direct To Debit payment create  
       * Direct To Debit payment status   
       * Direct To Debit payment cancel

  - name: Virtual Card Program (VCP)
    description: |
      Virtual cards are one way that Echo facilitates payments from the Payor to the Provider. The Payor or Provider may have questions on whether a card has been used, what the card balance is, and if the card is active. For these types of inquiries, there is an API endpoint for card status and transactions. 

      There are several situations where a Provider or Payor may want to cancel (Block) the card. The Payor may want to issue another form of payment directly to the Provider through their own process. The Provider may prefer a check or another form of payment (Block and Reissue), or the Provider may want to cancel their current card and opt out of all future cards (Block and OptOut). These types of card-blocking scenarios can be done through the following API endpoints -- Block, BlockAndReissue, and BlockAndOptOut.

      virtual card program has two end points:
        * Virtual Card  Activity 
        * Virtual Card  Cancel
   
  - name: Venmo
    description: |
      Venmo is a payment app available on iPhones and Android phones that allows for the quick and easy exchange of money. A user with a Venmo account can transfer funds to the Payee bank account without needing cash or checks.  
      Venmo accounts can be linked to credit cards, debit cards, or checking accounts. Venmo is more like a digital wallet where funds are held as a Venmo balance in the checking account.  
      Venmo has three endpoints:  
      •	Venmo payment create  
      •	Venmo payment status  
      •	Venmo payment cancel  
    
        
  - name: Zelle
    description: |
        Zelle helps transfer funds between bank accounts instantly through the Zelle app with just an email address or mobile number. The amount is directly deposited into the Payee’s bank account. Money sent with Zelle is typically available to a Zelle enrolled Payee within minutes. 
        Zelle has three endpoints:
        * Zelle payment create
        * Zelle payment status
        * Zelle payment cancel
    
  - name: Universal Payment Cancel
    description: | 
        The Universal Payment Cancel endpoint allows the API user to access and cancel a payment that may be Direct to Debit, Venmo, Zelle, or a Virtual Card based on the Library method. This endpoint helps validate and call a particular API internally based on the unique Payor Reference ID. This is used for in-house application only.     

  - name: Universal Payment Status
    description: | 
        The Universal Payment Status endpoint allows the API user to access and get the status of a payment that may be Direct to Debit, Venmo, Zelle, or a Virtual Card based on the library method. This endpoint helps validate and call a particular API internally based on the unique Payor Reference ID. This is used for in-house application only.

        
