required:
  - APIFormIdentifierID
  - EchoSecAuthorizationToken
  - UserName
  - ActionType
type: object
properties:
 
  APIFormIdentifierID: 
    type: string
    description:  The API form identifier is 84. This is a unique identifier that serves the purpose of identifying a particular request. It helps identify and map the request to the correct endpoint.
    maxLength: 50
    minLength: 1
  
  UserName: 
    type: string
    description: This is a unique name for each account and enables the clearinghouse user/admin to maintain personal settings and identification with the portal.
    maxLength: 50
    minLength: 16
    
  ActionType: 
    type: string
    maxLength: 100
    minLength: 1
    description: The value for this field can be either GetCHSettings or UpdateCHSettings.
    
  EchoSecAuthorizationToken: 
    type: string
    description: This is a unique name for each account and enables the user to maintain personal settings and identification with the portal.
    maxLength: 100
    minLength: 1

  StatusId: 
    type: boolean
    description: StatusId
  
  BroadcastEnrollmentStatus: 
    type: boolean
    description: BroadcastEnrollmentStatus
    
  DisableEFTEnrollmentStatus: 
    type: boolean
    description: DisableEFTEnrollmentStatus

  MFAOptions: 
    type: string
    description: MFAOptions
    maxLength: 100

