post:
  tags:
    - Clearinghouse Portal 
     
  summary: Clearinghouse Portal - Get Update CH Settings
  x-internal: true
  operationId: GetUpdateCHSettings
  parameters:
    - name: x-RequestUrl
      in: header
      required: true
      schema:
        type: string
        $ref: ../../components/headers/xRequestUrl.yaml
    - name: x-RequestFromAPP
      in: header
      required: true
      schema:
        type: string
        $ref: ../../components/headers/xRequestFromAPP.yaml
    - name: x-Authorization
      in: header
      required: true
      schema:
        type: string
        $ref: ../../components/headers/xAuthorization.yaml
    - name: x-AccessId
      in: header
      required: false
      schema:
        type: string
        $ref: ../../components/headers/xAccessId.yaml
        descritption: |
          
  requestBody:
    required: true
    content:
      application/json:
        schema: 
          $ref: ../../components/schemas/ClearingHousePortal/Request/GetUpdateCHSettingsRequest.yaml
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/ClearingHousePortal/Response/GetUpdateCHSettingsResponse.yaml
          examples:
            mapName_001:   
              description: Please scroll the above dropdown list for more response codes          
              summary: "001"
              value:
                ReponseCode: "001"
                ReponseCodeDesc: Successful Transaction
                ResponseTransactionID: Transaction Number
                TransLog:                  
                -  TransResponseCode: "001"
                   TransResponseCodeDesc: Success.
                    
            mapName_900:   
              description: Please scroll the above dropdown list for more response codes          
              summary: "900"
              value:
                ReponseCode: "900"
                ReponseCodeDesc: Transaction Failed
                ResponseTransactionID: Transaction Number
                TransError:  
                  -  ErrorCode: "6"
                     ErrorDesc: Invalid JSON String
                  -  ErrorCode: "1035"
                     ErrorDesc: Invalid or Missing UserName
                  -  ErrorCode: "1039"
                     ErrorDesc: Invalid or Missing EchoSecurityAuthToken
                  -  ErrorCode: "1099"
                     ErrorDesc: Invalid or Missing Action Type
                  -  ErrorCode: "1071"
                     ErrorDesc: Invalid or Missing ClearingHouseName

