type: object
properties:
  This is the Response for Response Code 001:
    type: object
    properties:
      ReponseCode:
        type: string
        description: Response Code 001
      ReponseCodeDesc:
        type: string
        description: Successful Transaction
      ResponseTransactionID:
        type: string
        description: Transaction Number
      TransLog for Payment Response Code 001:
        type: object
        properties:
          TransResponseCode:
            type: string
            description: Transaction response code number
          TransResponseCodeDesc:
            type: string
            description: Success.
            
  This is the Response for Response Code 900:
    type: object
    properties:
      ReponseCode:
        type: string
        description: Response Code 900
      ReponseCodeDesc:
        type: string
        description: Transaction Failed
      ResponseTransactionID:
        type: string
        description: Transaction Number
      TransError for Payment Response Code 900:
        type: object
        properties:
          ErrorCode:
            type: string
            description:  Error code number
          ErrorDesc:
           type: string
           description: Error description
      
      TransError JSON Validation Failed Code 6:
        type: object
        properties:
          ErrorCode:
            type: integer
            description: "6"
          ErrorDesc:
            type: string
            description: Invalid JSON String

      TransError JSON Validation Failed Code 1039:
        type: object
        properties:
          ErrorCode:
            type: integer
            description: "1039"
          ErrorDesc:
            type: string
            description: Invalid or Missing EchoSecurityAuthToken
                
      TransError JSON Validation Failed Code 1035:
        type: object
        properties:
          ErrorCode:
            type: integer
            description: "1035"
          ErrorDesc:
            type: string
            description: Invalid or Missing UserName

      TransError JSON Validation Failed Code 1099:
        type: object
        properties:
          ErrorCode:
            type: integer
            description: "1099"
          ErrorDesc:
            type: string
            description: Invalid or Missing Action Type
      
      TransError JSON Validation Failed Code 1071:
        type: object
        properties:
          ErrorCode:
            type: integer
            description: "1071"
          ErrorDesc:
            type: string
            description: Invalid or Missing ClearingHouseName

      